name: Test with pip environment

on:
  - push
  - pull_request

jobs:
  qa-linux-pip:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10"]

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix-version }}
      - name: Install development dependencies
        run: pip install -r requirements-dev.txt
      - name: Lint Python source code
        run: flake8 .
      - name: Format with black formatter
        run: black .
      - name: Run tests
        run: pytest
